plasonup/core/urls.py
from django.conf.urls import url
from django.urls import path

#Import personales
from . import views

app_name = 'core'
urlpatterns = [
    #Basicas:
    url(r'^$', views.home, name='home'),
    path('completar/', views.get_tarjeta, name='get_tarjeta'),
    path('consultas/', views.get_consultas, name='get_consultas'),
    path('completar/<int:benef_id>/<int:benef_tarjeta>/', views.completar_beneficiario, name='completar_beneficiario'),
    path('completar/<int:benef_id>/<int:benef_tarjeta>/<int:familiar_id>', views.delete_familiar, name='delete_familiar'),
    
    #File uploads:
    path('upload_escuelas/', views.upload_escuelas, name='upload_escuelas'),
    path('upload_tarjetas/', views.upload_tarjetas, name='upload_tarjetas'),
        
    #File Download
    path('download_beneficiarios/', views.download_beneficiarios, name='download_beneficiarios'),
    path('download_familiares/', views.download_familiares, name='download_familiares'),
    path('download_conyuges/', views.download_conyuges, name='download_conyuges'),
    
]

plasonup/plasonup/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #Extras
    url(r'^tinymce/', include('tinymce.urls')),
    #Apps Propias
    path('', include('core.urls', namespace='core_app')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plasonup/core/models.py
#Imports de python

#Realizamos imports de Django
from django.db import models
from django.utils import timezone
from .choices import TIPO_TRABAJO, TIPO_BENEFICIO
from django.urls import reverse

# Create your models here.
class Departamento(models.Model):
    nombre = models.CharField('Nombre', max_length=8, blank=True, null=True)
    def __str__(self):
        return self.nombre

class Localidad(models.Model):
    departamento = models.ForeignKey(Departamento, on_delete=models.SET_NULL, blank=True, null=True)
    nombre = models.CharField('Nombre', max_length=8, blank=True, null=True)
    def __str__(self):
        return self.nombre

class Sector(models.Model):
    nombre = models.CharField('Nombre', max_length=8, blank=True, null=True)
    def __str__(self):
        return self.nombre

class Ambito(models.Model):
    nombre = models.CharField('Nombre', max_length=8, blank=True, null=True)
    def __str__(self):
        return self.nombre

class Escuela(models.Model):
    cueanexo = models.IntegerField('CUE',)
    nombre = models.CharField('Nombre', max_length=100)
    localidad = models.ForeignKey(Localidad, on_delete=models.SET_NULL, blank=True, null=True)
    sector = models.ForeignKey(Sector, on_delete=models.SET_NULL, blank=True, null=True)
    ambito = models.ForeignKey(Ambito, on_delete=models.SET_NULL, blank=True, null=True)
    def __str__(self):
        return self.nombre + ' de ' + self.localidad.nombre

class Beneficiario(models.Model):
    tarjeta = models.CharField('Tarjeta', max_length=100, unique=True)
    dni = models.CharField('DNI', max_length=8,)
    cuil = models.CharField('CUIL', max_length=13, blank=True, null=True)
    apellidos = models.CharField('Apellidos', max_length=100)
    nombres = models.CharField('Nombres', max_length=100)
    tel_celular = models.CharField('Telefono Celular', max_length=100, blank=True, null=True)
    tel_fijo = models.CharField('Telefono Fijo', max_length=100, blank=True, null=True)
    email = models.EmailField('Correo Personal', blank=True, null=True)
    fecha_nacimiento = models.DateField('Fecha de Nacimiento', blank=True, null=True)
    localidad = models.ForeignKey(Localidad, on_delete=models.SET_NULL, blank=True, null=True)
    direccion_calle = models.CharField('Calle', max_length=50, blank=True, null=True)
    direccion_numero = models.CharField('Numero', max_length=50, blank=True, null=True)
    direccion_barrio = models.CharField('Barrio', max_length=50, blank=True, null=True)
    direccion_manzana = models.CharField('Manzana', max_length=50, blank=True, null=True)
    direccion_lote = models.CharField('Lote', max_length=50, blank=True, null=True)
    def __str__(self):
        return self.apellidos + ' ' + self.nombres
    def get_absolute_url(self):
        return reverse('completar_beneficiario', kwargs={'benef_id': self.id, 'benef_tarjeta': self.tarjeta})
    

class Parentezco(models.Model):
    nombre = models.CharField('tipo', max_length=100)
    def __str__(self):
        return self.nombre

class Criticidad(models.Model):
    nombre = models.CharField('tipo', max_length=100)
    def __str__(self):
        return self.nombre

class Familiar(models.Model):
    beneficiario = models.ForeignKey(Beneficiario, on_delete=models.CASCADE, related_name='familiares')
    dni = models.CharField('DNI', max_length=8)
    apellidos = models.CharField('Apellidos', max_length=100)
    nombres = models.CharField('Nombres', max_length=100)
    fecha_nacimiento = models.DateField('Fecha de Nacimiento', blank=True, null=True)
    escuela = models.ForeignKey(Escuela, on_delete=models.SET_NULL, blank=True, null=True)
    parentezco = models.ForeignKey(Parentezco, on_delete=models.CASCADE)
    criticidad = models.ForeignKey(Criticidad, on_delete=models.SET_NULL, blank=True, null=True)
    trabajo = models.CharField('Tipo de Trabajo', choices=TIPO_TRABAJO, max_length=2, default='NT', null=True, blank=True)    
    beneficio = models.CharField('Recibe beneficio', choices=TIPO_BENEFICIO, max_length=3 , default='NT', null=True, blank=True)
    def __str__(self):
        return self.apellidos + ' ' + self.nombres


class Conyuge(models.Model):
    beneficiario = models.ForeignKey(Beneficiario, on_delete=models.CASCADE, related_name='conyuges')
    nombres = models.CharField('Nombres', max_length=100)
    apellidos = models.CharField('Apellidos', max_length=100)
    dni = models.CharField('DNI', max_length=8,)
    cuil = models.CharField('CUIL', max_length=13, blank=True, null=True)
    trabajo = models.CharField('Tipo de Trabajo', choices=TIPO_TRABAJO, max_length=2, default='NT', null=True, blank=True)    
    beneficio = models.CharField('Recibe beneficio', choices=TIPO_BENEFICIO, max_length=3 , default='NT', null=True, blank=True)
    def __str__(self):
        return self.apellidos + ' ' + self.nombres

plasonup/core/views.py
#Modulos Python
import csv
#Modulos Django
from django.shortcuts import render
from django.contrib.admin.views.decorators import staff_member_required
from django.http import HttpResponse
from django.shortcuts import redirect
from django.contrib import messages 
#Imports del proyecto
from .decoradores import superuser_required
from .forms import UploadCsv
from .models import Departamento, Localidad, Escuela
from .models import Sector, Ambito
from .models import Beneficiario, Familiar, Conyuge
from .forms import TarjetaForm, BeneficiarioForm, FamiliarFormset, ConyugeFormset
# Create your views here.
def home(request):
    return render(request, 'home.html', {})

@superuser_required
def upload_escuelas(request):
    titulo = "Gestion Masiva de Escuelas"
    if request.method == "GET":
        form = UploadCsv()
        return render(request, 'upload_csv.html', {'titulo': titulo, 'form': form,})
    elif request.method == "POST":
        form = UploadCsv(request.POST, request.FILES)
        if form.is_valid():
            count = 0
            csv_file = form.cleaned_data['csvfile']
            file_data = csv_file.read().decode("utf-8")
            lines = file_data.split("\n")
            #Procesamos el archivo
            #0-CUEANEXO	1-NOMBRE	2-CALLE	3-NRO	4-BARRIO	5-C.P.	6-LOCALIDAD	7-DEPARTAMENTO	8-TELEFONO	9-REGION	10-SECTOR	11-AMBITO
            escuelas = []
            for line in lines:
                line=line.split(',')
                if line[0]:
                    escuela = Escuela()
                    escuela.cueanexo = line[0]
                    escuela.nombre = line[1]
                    escuela.localidad = Localidad.objects.get_or_create(
                        departamento=Departamento.objects.get_or_create(nombre=line[7])[0],
                        nombre=line[6],
                    )[0]
                    escuela.sector = Sector.objects.get_or_create(nombre=line[10])[0]
                    escuela.ambito = Ambito.objects.get_or_create(nombre=line[11])[0]
                    escuelas.append(escuela)
            count = len(escuelas)
            Escuela.objects.bulk_create(escuelas)
            return render(request, "upload_csv.html", {'titulo': titulo, 'count': count, })
        else:
            message = form.errors
            return render(request, "upload_csv.html", {'titulo': titulo, 'message': message, })

@superuser_required
def upload_tarjetas(request):
    titulo = "Gestion Masiva de Tarjetas de Beneficiarios"
    if request.method == "GET":
        form = UploadCsv()
        return render(request, 'upload_csv.html', {'titulo': titulo, 'form': form, })
    elif request.method == "POST":
        form = UploadCsv(request.POST, request.FILES)
        if form.is_valid():
            count = 0
            csv_file = form.cleaned_data['csvfile']
            file_data = csv_file.read().decode("utf-8")
            lines = file_data.split("\n")
            #Procesamos el archivo
            #Beneficiario.objects.all().delete()
            beneficiarios = []
            #0-Apellido	1-Nombre	2-DNI	3-tarjeta	4-localidad
            tarjeta_cargada = []
            for line in lines:
                line=line.split(',')
                if line[0]:
                    beneficiario = Beneficiario()                        
                    beneficiario.apellidos = line[0]                    
                    beneficiario.tarjeta = line[1]
                    beneficiario.dni = line[2]
                    beneficiario.nombres = line[3]
                    if beneficiario.tarjeta not in tarjeta_cargada:
                        beneficiarios.append(beneficiario)
                        tarjeta_cargada.append(beneficiario.tarjeta)
            count = len(beneficiarios)
            Beneficiario.objects.bulk_create(beneficiarios)
            return render(request, "upload_csv.html", {'titulo': titulo, 'count': count, })
        else:
            message = form.errors
            return render(request, "upload_csv.html", {'titulo': titulo, 'message': message, })


@superuser_required
def download_beneficiarios(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="beneficiarios.csv"'
    writer = csv.writer(response)
    writer.writerow(['LISTADO DE BENEFICIARIOS'])
    writer.writerow(['DNI', 'Tarjeta', 'Cuil', 'Apellido', 'Nombre', 'Tel Celular' ,'Tel Fijo', 'Email', 'Fecha Nacimiento', 'Tiene Conyuge', 'Localidad', 'Departamento', 'Direccion Calle', 'Direccion Numero', 'Barrio', 'Manzana', 'Lote'])
    beneficiarios = Beneficiario.objects.all()
    beneficiarios = beneficiarios.select_related('localidad','localidad__departamento')
    for benef in beneficiarios:
        try:
            conyuge = Conyuge.objects.get(beneficiario_id = benef.id)
            tmp_conyu = 'SI' 
        except Conyuge.DoesNotExist:
            tmp_conyu = 'NO'      

        if benef.localidad: 
            tmp_localidad = benef.localidad.nombre
            tmp_departamento = benef.localidad.departamento.nombre
        else: 
            tmp_localidad = ''
            tmp_departamento = ''
        
        writer.writerow([
            benef.dni,
            benef.tarjeta,
            benef.cuil,
            benef.apellidos,
            benef.nombres,
            benef.tel_celular,
            benef.tel_fijo,
            benef.email,
            benef.fecha_nacimiento,
            tmp_conyu,
            tmp_localidad,
            tmp_departamento,
            benef.direccion_calle,
            benef.direccion_numero,
            benef.direccion_barrio,
            benef.direccion_manzana,
            benef.direccion_lote,])
    return response   

@superuser_required
def download_familiares(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="familiares.csv"'
    writer = csv.writer(response)
    writer.writerow(['LISTADO DE FAMILIARES DE BENEFICIARIOS'])
    writer.writerow(['Beneficiario_DNI', 'Parentezco', 'DNI', 'Apellidos', 'Nombres', 'Fecha Nacimiento', 'Escuela CUE', 'Criticidad'])
    familiares = Familiar.objects.all()
    familiares = familiares.select_related('parentezco', 'criticidad', 'escuela','beneficiario')
    for familiar in familiares:
        if familiar.escuela:
            tmp_escuela = familiar.escuela.cueanexo
        else:
            tmp_escuela = ''
        if familiar.criticidad:
            tmp_criticidad = familiar.criticidad.nombre
        else:
            tmp_criticidad = ''

        writer.writerow([
            familiar.beneficiario.dni,
            familiar.parentezco.nombre,
            familiar.dni,
            familiar.apellidos,
            familiar.nombres,
            familiar.fecha_nacimiento,
            tmp_escuela,
            tmp_criticidad])
    return response

@superuser_required
def download_conyuges(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="conyuges.csv"'
    writer = csv.writer(response)
    writer.writerow(['LISTADO DE CONYUGES DE BENEFICIARIOS'])
    writer.writerow(['Beneficiario_DNI', 'apellido_beneficiario', 'nombre_beneficiario', 'nombres', 'apellidos', 'dni', 'cuil', 'trabajo', 'beneficio'])
    conyuges = Conyuge.objects.all()
    conyuges = conyuges.select_related('beneficiario')
    for conyuge in conyuges:
        if conyuge.trabajo == 'NT':
            con_trabajo =  'No trabaja'
        if conyuge.trabajo == 'TB':
            con_trabajo = 'Trabajo en Blanco'
        if conyuge.trabajo == 'TI':
            con_trabajo = 'Trabajo Informal'
        if conyuge.trabajo == 'O':
            con_trabajo = 'Otro'

        if conyuge.beneficio == 'NT':
            con_ben =  'No tiene'
        if conyuge.beneficio == 'TAF':
            con_ben = 'Titular de asignacion familiar'
        if conyuge.beneficio == 'TBP':
            con_ben = 'Titular de beca progresar'
        if conyuge.beneficio == 'PD':
            con_ben = 'Cobra prestacion por desempleo'
        if conyuge.beneficio == 'TES':
            con_ben = 'Programa de Empleo de la Secretaria de Trabajo, Empleo y Seguridad Social'
        if conyuge.beneficio == 'J':
            con_ben = 'Jubilado'
        if conyuge.beneficio == 'O':
            con_ben = 'Otro'

        writer.writerow([
            conyuge.beneficiario.dni,
            conyuge.beneficiario.apellidos,
            conyuge.beneficiario.nombres,
            conyuge.nombres,
            conyuge.apellidos,
            conyuge.dni,            
            conyuge.cuil,
            con_trabajo,
            con_ben])
    return response

def get_tarjeta(request):
    if request.method == 'GET':
        form = TarjetaForm()
        return render(request, 'extras/generic_form.html', {'titulo': "INGRESE DATOS", 'form': form, 'boton': "ACCEDER", })
    elif request.method == 'POST':
        form = TarjetaForm(request.POST)
        if form.is_valid():
            benef_tarj = form.cleaned_data.get('tarjeta')
            benef_dni = form.cleaned_data.get('dni')
            try:
                beneficiario = Beneficiario.objects.get(tarjeta=benef_tarj, dni=benef_dni)
                return redirect('core:completar_beneficiario', benef_id=beneficiario.id, benef_tarjeta=benef_tarj)
            except Beneficiario.DoesNotExist:
                return render(request, 'extras/generic_form.html', {'titulo': "INGRESE DATOS", 'form': form, 'boton': "ACCEDER", 'message': 'No existe beneficiario con estos datos.'})
        else:            
            return render(request, 'extras/generic_form.html', {'titulo': "INGRESE DATOS", 'form': form, 'boton': "ACCEDER",'message': 'Formulario no valido.'})

#def completar_beneficiario(request, benef_id, benef_tarjeta):
    #message = ''
    #template_name = 'beneficiarios.html'
    #if request.method == 'GET':
        #message = 'COMPLETE SUS DATOS'

plasonup/core/templates/extras/generic_form-nobase.html
{% load static %}
{% load form_tags %}

{% block custom_head %}

<head>
    <!-- mobile responsive meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <style>
        @media screen and (max-width: 720px){
            .page-wrapper {
              width: 100%;
            }
        }
    </style>    
</head>



{% endblock %}

{% block content %}

{% comment %}
    <section class="formulario">
        <section class="formulario-container">
            <h2>{{titulo}}</h2>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form.hidden_fields %}
                    {{ field }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    
                    {% abrir_alineado form field as abrir %}
                    {% if abrir %}
                        <div class="row">
                    {% endif %}

                        {% calcular_ancho form field as ancho %}
                        <div class="col-sm-{{ancho}} no-padding enlinea">
                            {{ field.label_tag }}
                            {{ field }}
                            {% for error in field.errors %}
                                <p class="error">{{ error }}</p>
                            {% endfor %}
                        </div>

                    {% cerrar_alineado form field as cerrar %}
                    {% if cerrar %}
                        </div>
                    {% endif %}
                
                {% endfor %}
                <br>
                {% for error in form.non_field_errors %}
                    <p class="error">
                        {{error|escape}}
                    </p>
                {% endfor %}
                {% if message %}
                    <p>{{message}}</p>
                {% endif %} 
                <br>
                <button type="submit">{{boton}}</button>
            </form>
        </section>
    </section>
{% endcomment %}

<div class="limiter">    
    <div class="container-login100">
        <div class="wrap-login100">            
            <form class="login100-form validate-form" method="post" enctype="multipart/form-data" onSubmit="return validar();" id="formjquery">
                {% csrf_token %}
                <span class="login100-form-title p-b-26">
                {{titulo}}                   
                </span>
                <span class="login100-form-title p-b-48">                    
                    <i class="zmdi zmdi-font"></i>
                </span>

                <div class="wrap-input100 validate-input">
                    <input class="input100" type="text" name="tarjeta" required id="id_tarjeta" placeholder="INGRESE SU TARJETA">
                    <span class="focus-input100"></span>
                </div>

                <div class="wrap-input100 validate-input">                    
                    <input class="input100" type="text" name="dni" required id="id_dni" placeholder="INGRESE SU DNI">
                    <span class="focus-input100"></span>
                </div>
                <br>
                {% for error in form.non_field_errors %}
                    <p class="error">
                        {{error|escape}}
                    </p>
                {% endfor %}
                {% if message %}
                    <p>{{message}}</p>
                {% endif %} 
                <br>
                <div class="container-login100-form-btn">
                    <div class="wrap-login100-form-btn">
                        <div class="login100-form-bgbtn"></div>
                        <button type="submit" class="login100-form-btn">
                            {{boton}}
                        </button>
                    </div>
                </div>               
            </form>
        </div>
    </div>
</div>


<div id="dropDownSelect1"></div>

{% endblock %}

  

<script>
    function validar(){
        
        //Almacenamos los valores
        tarjeta=$('#id_tarjeta').val();               
        
       //Comprobamos la longitud de caracteres
        if (tarjeta.length == 9){
            return true;
        }
        else {
            alert('Debe ingresar los últimos 9 caracteres de su tarjeta');
            return false;
            
        }        
    }
</script>

plasonup/core/templates/extras/generic_form.html
{% extends 'base.html' %}

{% block content %}

<!-- Header - set the background image for the header in the line below -->
<!-- <header class="py-5 bg-image-full" style="background-image: url('http://spi.jujuy.gob.ar/wp-content/uploads/sites/53/2019/12/cabecera.jpg');">
<div style="height: 300px;"></div> -->
<!--<img class="img-fluid d-block mx-auto" src="http://placehold.it/200x200&text=Logo" alt="">-->
</header>
    <div class="alert alert-danger" role="alert">
        <h3>¡IMPORTANTE! ESTE TRÁMITE ES PARA LOS BENEFICIARIOS QUE YA SE HAN INSCRIPTO ANTERIORMENTE Y QUE CUENTAN CON LA TARJETA ACTIVA.</h3> 
        <br>
        <h2><center>INGRESE LOS ÚLTIMOS 9 DÍGITOS DE SU TARJETA</center></h2>   
    </div>
    {% include 'extras/generic_form-nobase.html' %}

{% endblock %}