plasonup/core/urls.py
from django.conf.urls import url
from django.urls import path

#Import personales
from . import views

app_name = 'core'
urlpatterns = [
    #Basicas:
    url(r'^$', views.home, name='home'),
    path('completar/', views.get_tarjeta, name='get_tarjeta'),
    path('consultas/', views.get_consultas, name='get_consultas'),
    path('completar/<int:benef_id>/<int:benef_tarjeta>/', views.completar_beneficiario, name='completar_beneficiario'),
    path('completar/<int:benef_id>/<int:benef_tarjeta>/<int:familiar_id>', views.delete_familiar, name='delete_familiar'),
    
    #File uploads:
    path('upload_escuelas/', views.upload_escuelas, name='upload_escuelas'),
    path('upload_tarjetas/', views.upload_tarjetas, name='upload_tarjetas'),
        
    #File Download
    path('download_beneficiarios/', views.download_beneficiarios, name='download_beneficiarios'),
    path('download_familiares/', views.download_familiares, name='download_familiares'),
    path('download_conyuges/', views.download_conyuges, name='download_conyuges'),
    
]

plasonup/plasonup/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #Extras
    url(r'^tinymce/', include('tinymce.urls')),
    #Apps Propias
    path('', include('core.urls', namespace='core_app')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plasonup/core/forms.py
#Imports Python
from datetime import timedelta
import datetime
#Imports del framework Django
from django.utils import timezone
from django import forms
from django.forms import ModelForm, modelformset_factory
from django.forms.models import inlineformset_factory
from .choices import TIPO_TRABAJO, TIPO_BENEFICIO

#Imports de la app:
from .models import Beneficiario, Familiar, Conyuge
#Definimos nuestros formularios
class UploadCsv(forms.Form):
    csvfile = forms.FileField(widget=forms.FileInput(attrs={'accept': ".csv"}))

class TarjetaForm(forms.Form):
    tarjeta = forms.IntegerField(min_value=000000000, max_value=999999999)
    dni = forms.IntegerField()

class BeneficiarioForm(forms.ModelForm):    
    class Meta:
        model = Beneficiario
        fields = '__all__'
        widgets = {
            'cuil': forms.TextInput(attrs={'placeholder': 'Introduzca CUIL'}),
            'apellidos': forms.TextInput(attrs={'placeholder': 'Introduzca Apellido'}),
            'nombres': forms.TextInput(attrs={'placeholder': 'Introduzca Nombre'}),
            'tel_celular': forms.TextInput(attrs={'placeholder': 'Introduzca su número de celular'}),
            'tel_fijo': forms.TextInput(attrs={'placeholder': 'Introduzca su número de teléfono fijo'}),
            'email': forms.TextInput(attrs={'placeholder': 'Introduzca su email'}),
            'fecha_nacimiento': forms.DateInput(attrs={'value': datetime.datetime.now().strftime('%d/%m/%Y')}),
            'direccion_calle': forms.TextInput(attrs={'placeholder': 'Introduzca calle donde vive'}),
            'direccion_numero': forms.TextInput(attrs={'placeholder': 'Introduzca Número'}),
            'direccion_barrio': forms.TextInput(attrs={'placeholder': 'Introduzca Barrio'}),
            'direccion_manzana': forms.TextInput(attrs={'placeholder': 'Introduzca Manzana'}),
            'direccion_lote': forms.TextInput(attrs={'placeholder': 'Introduzca Lote'}),
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance.pk:
            self.fields['tarjeta'].widget.attrs.update({'readonly': True})
            self.fields['dni'].widget.attrs.update({'readonly': True})


class FamiliarForm(forms.ModelForm):
    class Meta:
        model = Familiar
        fields = '__all__'
        exclude = ('beneficiario', 'trabajo', 'beneficio',)

class ConyugeForm(forms.ModelForm):
    class Meta:
        model = Conyuge
        fields = '__all__'
        exclude = ('beneficiario',)

FamiliarFormset = inlineformset_factory(Beneficiario, Familiar,  FamiliarForm, extra=2, can_delete = False)
ConyugeFormset = inlineformset_factory(Beneficiario, Conyuge, ConyugeForm, extra=2, can_delete = False)

plasonup/core/views.py
#Modulos Python
import csv
#Modulos Django
from django.shortcuts import render
from django.contrib.admin.views.decorators import staff_member_required
from django.http import HttpResponse
from django.shortcuts import redirect
from django.contrib import messages 
#Imports del proyecto
from .decoradores import superuser_required
from .forms import UploadCsv
from .models import Departamento, Localidad, Escuela
from .models import Sector, Ambito
from .models import Beneficiario, Familiar, Conyuge
from .forms import TarjetaForm, BeneficiarioForm, FamiliarFormset, ConyugeFormset
# Create your views here.
def home(request):
    return render(request, 'home.html', {})

@superuser_required
def upload_escuelas(request):
    titulo = "Gestion Masiva de Escuelas"
    if request.method == "GET":
        form = UploadCsv()
        return render(request, 'upload_csv.html', {'titulo': titulo, 'form': form,})
    elif request.method == "POST":
        form = UploadCsv(request.POST, request.FILES)
        if form.is_valid():
            count = 0
            csv_file = form.cleaned_data['csvfile']
            file_data = csv_file.read().decode("utf-8")
            lines = file_data.split("\n")
            #Procesamos el archivo
            #0-CUEANEXO	1-NOMBRE	2-CALLE	3-NRO	4-BARRIO	5-C.P.	6-LOCALIDAD	7-DEPARTAMENTO	8-TELEFONO	9-REGION	10-SECTOR	11-AMBITO
            escuelas = []
            for line in lines:
                line=line.split(',')
                if line[0]:
                    escuela = Escuela()
                    escuela.cueanexo = line[0]
                    escuela.nombre = line[1]
                    escuela.localidad = Localidad.objects.get_or_create(
                        departamento=Departamento.objects.get_or_create(nombre=line[7])[0],
                        nombre=line[6],
                    )[0]
                    escuela.sector = Sector.objects.get_or_create(nombre=line[10])[0]
                    escuela.ambito = Ambito.objects.get_or_create(nombre=line[11])[0]
                    escuelas.append(escuela)
            count = len(escuelas)
            Escuela.objects.bulk_create(escuelas)
            return render(request, "upload_csv.html", {'titulo': titulo, 'count': count, })
        else:
            message = form.errors
            return render(request, "upload_csv.html", {'titulo': titulo, 'message': message, })

@superuser_required
def upload_tarjetas(request):
    titulo = "Gestion Masiva de Tarjetas de Beneficiarios"
    if request.method == "GET":
        form = UploadCsv()
        return render(request, 'upload_csv.html', {'titulo': titulo, 'form': form, })
    elif request.method == "POST":
        form = UploadCsv(request.POST, request.FILES)
        if form.is_valid():
            count = 0
            csv_file = form.cleaned_data['csvfile']
            file_data = csv_file.read().decode("utf-8")
            lines = file_data.split("\n")
            #Procesamos el archivo
            #Beneficiario.objects.all().delete()
            beneficiarios = []
            #0-Apellido	1-Nombre	2-DNI	3-tarjeta	4-localidad
            tarjeta_cargada = []
            for line in lines:
                line=line.split(',')
                if line[0]:
                    beneficiario = Beneficiario()                        
                    beneficiario.apellidos = line[0]                    
                    beneficiario.tarjeta = line[1]
                    beneficiario.dni = line[2]
                    beneficiario.nombres = line[3]
                    if beneficiario.tarjeta not in tarjeta_cargada:
                        beneficiarios.append(beneficiario)
                        tarjeta_cargada.append(beneficiario.tarjeta)
            count = len(beneficiarios)
            Beneficiario.objects.bulk_create(beneficiarios)
            return render(request, "upload_csv.html", {'titulo': titulo, 'count': count, })
        else:
            message = form.errors
            return render(request, "upload_csv.html", {'titulo': titulo, 'message': message, })


@superuser_required
def download_beneficiarios(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="beneficiarios.csv"'
    writer = csv.writer(response)
    writer.writerow(['LISTADO DE BENEFICIARIOS'])
    writer.writerow(['DNI', 'Tarjeta', 'Cuil', 'Apellido', 'Nombre', 'Tel Celular' ,'Tel Fijo', 'Email', 'Fecha Nacimiento', 'Tiene Conyuge', 'Localidad', 'Departamento', 'Direccion Calle', 'Direccion Numero', 'Barrio', 'Manzana', 'Lote'])
    beneficiarios = Beneficiario.objects.all()
    beneficiarios = beneficiarios.select_related('localidad','localidad__departamento')
    for benef in beneficiarios:
        try:
            conyuge = Conyuge.objects.get(beneficiario_id = benef.id)
            tmp_conyu = 'SI' 
        except Conyuge.DoesNotExist:
            tmp_conyu = 'NO'      

        if benef.localidad: 
            tmp_localidad = benef.localidad.nombre
            tmp_departamento = benef.localidad.departamento.nombre
        else: 
            tmp_localidad = ''
            tmp_departamento = ''
        
        writer.writerow([
            benef.dni,
            benef.tarjeta,
            benef.cuil,
            benef.apellidos,
            benef.nombres,
            benef.tel_celular,
            benef.tel_fijo,
            benef.email,
            benef.fecha_nacimiento,
            tmp_conyu,
            tmp_localidad,
            tmp_departamento,
            benef.direccion_calle,
            benef.direccion_numero,
            benef.direccion_barrio,
            benef.direccion_manzana,
            benef.direccion_lote,])
    return response   

@superuser_required
def download_familiares(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="familiares.csv"'
    writer = csv.writer(response)
    writer.writerow(['LISTADO DE FAMILIARES DE BENEFICIARIOS'])
    writer.writerow(['Beneficiario_DNI', 'Parentezco', 'DNI', 'Apellidos', 'Nombres', 'Fecha Nacimiento', 'Escuela CUE', 'Criticidad'])
    familiares = Familiar.objects.all()
    familiares = familiares.select_related('parentezco', 'criticidad', 'escuela','beneficiario')
    for familiar in familiares:
        if familiar.escuela:
            tmp_escuela = familiar.escuela.cueanexo
        else:
            tmp_escuela = ''
        if familiar.criticidad:
            tmp_criticidad = familiar.criticidad.nombre
        else:
            tmp_criticidad = ''

        writer.writerow([
            familiar.beneficiario.dni,
            familiar.parentezco.nombre,
            familiar.dni,
            familiar.apellidos,
            familiar.nombres,
            familiar.fecha_nacimiento,
            tmp_escuela,
            tmp_criticidad])
    return response

@superuser_required
def download_conyuges(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="conyuges.csv"'
    writer = csv.writer(response)
    writer.writerow(['LISTADO DE CONYUGES DE BENEFICIARIOS'])
    writer.writerow(['Beneficiario_DNI', 'apellido_beneficiario', 'nombre_beneficiario', 'nombres', 'apellidos', 'dni', 'cuil', 'trabajo', 'beneficio'])
    conyuges = Conyuge.objects.all()
    conyuges = conyuges.select_related('beneficiario')
    for conyuge in conyuges:
        if conyuge.trabajo == 'NT':
            con_trabajo =  'No trabaja'
        if conyuge.trabajo == 'TB':
            con_trabajo = 'Trabajo en Blanco'
        if conyuge.trabajo == 'TI':
            con_trabajo = 'Trabajo Informal'
        if conyuge.trabajo == 'O':
            con_trabajo = 'Otro'

        if conyuge.beneficio == 'NT':
            con_ben =  'No tiene'
        if conyuge.beneficio == 'TAF':
            con_ben = 'Titular de asignacion familiar'
        if conyuge.beneficio == 'TBP':
            con_ben = 'Titular de beca progresar'
        if conyuge.beneficio == 'PD':
            con_ben = 'Cobra prestacion por desempleo'
        if conyuge.beneficio == 'TES':
            con_ben = 'Programa de Empleo de la Secretaria de Trabajo, Empleo y Seguridad Social'
        if conyuge.beneficio == 'J':
            con_ben = 'Jubilado'
        if conyuge.beneficio == 'O':
            con_ben = 'Otro'

        writer.writerow([
            conyuge.beneficiario.dni,
            conyuge.beneficiario.apellidos,
            conyuge.beneficiario.nombres,
            conyuge.nombres,
            conyuge.apellidos,
            conyuge.dni,            
            conyuge.cuil,
            con_trabajo,
            con_ben])
    return response

def get_tarjeta(request):
    if request.method == 'GET':
        form = TarjetaForm()
        return render(request, 'extras/generic_form.html', {'titulo': "INGRESE DATOS", 'form': form, 'boton': "ACCEDER", })
    elif request.method == 'POST':
        form = TarjetaForm(request.POST)
        if form.is_valid():
            benef_tarj = form.cleaned_data.get('tarjeta')
            benef_dni = form.cleaned_data.get('dni')
            try:
                beneficiario = Beneficiario.objects.get(tarjeta=benef_tarj, dni=benef_dni)
                return redirect('core:completar_beneficiario', benef_id=beneficiario.id, benef_tarjeta=benef_tarj)
            except Beneficiario.DoesNotExist:
                return render(request, 'extras/generic_form.html', {'titulo': "INGRESE DATOS", 'form': form, 'boton': "ACCEDER", 'message': 'No existe beneficiario con estos datos.'})
        else:            
            return render(request, 'extras/generic_form.html', {'titulo': "INGRESE DATOS", 'form': form, 'boton': "ACCEDER",'message': 'Formulario no valido.'})

#def completar_beneficiario(request, benef_id, benef_tarjeta):
    #message = ''
    #template_name = 'beneficiarios.html'
    #if request.method == 'GET':
        #message = 'COMPLETE SUS DATOS'

plasonup/core/templates/base/footer.html
{% load static %}
{% block content %}
  <footer id="pie">
    <div class="social">

    </div>
    <div class="row">
      <div class="col-md-2">
      </div>
      <div class="col-md-2">
      </div>
      <div class="col-md-2">
      </div>
      <div class="col-md-2">
      </div>
      <div class="col-md-3">
        <a href="#">
        <img class="logo_unif" src="{% static 'img/logo_unif.png' %}" class="logo" style="margin-top: 10px; float: right;"/>
        </a>
      </div>
    </div>
  </footer>
{% endblock %}

plasonup/core/templates/base/head.html
{% load static %}
{% block content %}  
    <meta charset="utf-8">
    <title>{% block title %}plasonup{% endblock %}</title>
    
    {% if refresh %}<meta http-equiv="refresh" content="{{refresh}}"/>{%endif%}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/generic_form.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/lightbox.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/screen.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/menu.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}" />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>    
    <link rel="icon" href="{% static 'img/icons/favicon.ico' %}">
    <!-- Forms -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.datetimepicker.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/font.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}" />   
    <link rel="stylesheet" type="text/css" href="{% static 'css/customers.css' %}" />
    {% if form %}
      <link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}" />
      <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.maxlength.css' %}" />
    {% endif %}   
    
    <style type="text/css">
      @font-face {
        font-family: Archia;
        font-weight: normal;
        src: url({% static 'fonts/Archia-Regular.otf' %}) format('truetype');
        src: local({% static 'fonts/Archia-Regular.otf' %}) format('truetype');
     }
      @font-face {
        font-family: Archia;
        font-weight: bold;
        src: url({% static 'fonts/Archia-Bold.otf' %}) format('truetype');
        src: local({% static 'fonts/Archia-Bold.otf' %}) format('truetype');
     }
      @font-face {
        font-family: Archia;
        font-weight: lighter;
        src: url({% static 'fonts/Archia-Thin.otf' %}) format('truetype');
        src: local({% static 'fonts/Archia-Thin.otf' %}) format('truetype');
     }
    </style>
  
{% endblock %}

plasonup/core/templates/base/header.html
{% load static %} 

{% block content %}
<div class="portada">
   <!---- <img src="{% static 'img/logo.png' %}" alt="LogoSistema">
    {% if titulo_header %}
        <h1>{{titulo_header}}</h1>
    {% else %}
        <h1>Gobierno TV</h1>
    {% endif %}
    <div class="mobile">
        <img src="{% static 'img/logo.png' %}" alt="">
    </div>-->
</div>
{% endblock %}

plasonup/core/templates/base/menu.html
{% load static %}
{% block content %}
    <menu>
        <nav class="navbar navbar-static-top">
            <div class="container-fluid">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav-mobile" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="menu-logo" onclick="location.href='http://www.jujuy.gob.ar'" style="cursor: pointer">
                    <img src="{% static 'img/logo_menu.png' %}" />
                </div>
                <div class="collapse navbar-collapse mobile-only" id="nav-mobile" style="display:none">
                    <ul class="nav navbar-nav">
                        {% include "base/menu_opciones.html" %}
                    </ul>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        {% include "base/menu_opciones.html" %}
                    </ul>
                </div>
            </div>
        </nav>
    </menu>
{% endblock %}

plasonup/core/templates/base/menu_opciones.html
{% block content %}
    <li><a href="/">Inicio</a></li>
    <li><a href="http://prensa.jujuy.gob.ar/">Novedades</a></li>
    <li><a href="{% url 'core:get_consultas' %}" class="btn btn-primary">Consultas</a></li>

    {% if user.is_staff %}
        <li><a href="download_beneficiarios/" class="btn btn-success">Beneficiarios</a></li>
        <li><a href="download_familiares/" class="btn btn-danger">Familiares</a></li>
        <li><a href="download_conyuges/" class="btn btn-info">Conyuges</a></li>
        <li><a href="/admin">Admin</a></li>
    {% endif %}
{% endblock %}

plasonup/core/templates/base/scripts.html
{% load static %}
{% block content %}
    <scripts>
        <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery-ui.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script> 
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>        
        <script type="text/javascript" src="{% static 'js/masonry.pkgd.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/lightbox.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/change_links.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/popup.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/tabs.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/filter.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery.datetimepicker.full.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/date.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/type.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/numeric.js' %}"></script>    
        {% if form %}
            <script src='https://www.google.com/recaptcha/api.js'></script>
            <script type="text/javascript" src="{% static 'js/jquery.plugin.js' %}"></script>
            <script type="text/javascript" src="{% static 'js/jquery.maxlength.js' %}"></script>           
        {% endif %}       
    </scripts>
{% endblock %}